# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 065f106dabde945431d08074b67f5597a5b7d9dd016a6ac176f92d2a26a609ae2affc8381ff61c91bb0cc5127e81f7ca54c5de562b3b6884b9426d7da340e9bf

test:
  secret_key_base: 0a0c57fdae5f3e77efcbd96599eb64ab261ad5cc97f981ca3ad7a53de8430ec90dcb9a333d22c6a917f96e9938f43693a7af0923fb92848ec167e3906af9a3dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
